server:
  port: 1101
  servlet:
    context-path: /business

mybatis:
  type-aliases-package: com.kinth
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:sqlserver://123.207.86.17:1433;databasename=PropertyEncyclopedia
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Light.k3%190619

  
